vaadin/skeleton-starter-flow-spring

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/3)
=> Update version to 1.0.0.alpha7

.travis.yml, src/main/resources/META-INF/resources/frontend/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/4)
=> Enable travis

pom.xml, src/main/resources/META-INF/spring-devtools.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/5)
=> Add Spring boot devtools as a dependency.

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/8)
=> Update flow version.

pom.xml, src/main/resources/META-INF/spring-devtools.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/11)
=> Remove the workaround of the issue with dev tools

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/15)
=> Update platform version and exclude flow-server dependency from it

pom.xml
Update to Flow alpha11 and vaadin alpha8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/18)
=> Update to alpha11

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/19)
=> Update to version 1.0.0.alpha12

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/22)
=> Use Vaadin alpha9

pom.xml, src/main/java/com/vaadin/starter/skeleton/spring/ExampleServletInitializer.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/25)
=> Use Spring 2.0.0.M7 as defined by Vaadin alpha9

pom.xml, src/main/java/com/vaadin/starter/skeleton/spring/ExampleTemplate.java, src/main/java/com/vaadin/starter/skeleton/spring/MainView.java, src/main/java/com/vaadin/starter/skeleton/spring/MessageBean.java, src/main/resources/log4j.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/27)
=> Update platform version

src/main/java/com/vaadin/starter/skeleton/spring/MainView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/31)
=> Apply BodySize

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/38)
=> Added logger dependency

pom.xml, src/main/java/com/vaadin/starter/skeleton/spring/MainView.java, src/main/webapp/frontend/styles.html
Note this PR requires a new Vaadin10 release to compile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/36)
=> Add Lumo theme for spring starter

pom.xml, src/main/java/com/vaadin/starter/skeleton/spring/ExampleServletInitializer.java
Fix for #26.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/39)
=> Produced WAR should be deployable and work in production.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/43)
=> Remove unneeded clean from readme

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/44)
=> Correct port number in README

.gitignore, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/45)
=> Update platform version.

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/46)
=> Update plafrorm version.

src/main/webapp/frontend/styles/shared-styles.html
Make code in this project the same as in original starter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/48)
=> Use padding instead of margin

pom.xml, src/main/webapp/frontend/styles/shared-styles.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/49)
=> Update to new version

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/51)
=> Use Spring Boot 2.0.0

src/main/webapp/frontend/styles/shared-styles.html
Fixes #54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/57)
=> Correct shared-styles

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/58)
=> update platform version to beta3

pom.xml, src/main/java/com/vaadin/starter/skeleton/spring/MainView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/61)
=> Removed the @Theme declaration

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/66)
=> Update platform dependency to beta9

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/67)
=> Add Vaadin addons repository to pom.xml

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/69)
=> Use vaadin-maven-plugin

pom.xml
logback-classic is provided by spring boot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/76)
=> removed obsolete dependency

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/78)
=> Update platform dependency to RC 2

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/80)
=> Update platform to RC3

src/main/resources/application.properties
Fixes #85
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/86)
=> Add application.properties file

README.md, pom.xml, src/main/resources/META-INF/resources/frontend/src/README, src/main/resources/META-INF/resources/frontend/styles/README
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/89)
=> Adjust readmes

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/90)
=> Bump to V12 snapshot

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/97)
=> Bump v10 to 10.0.7

src/main/resources/application.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/101)
=> Disable the multipart resolver.

src/main/resources/application.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/102)
=> Disable the multipart resolver. (#101)

src/main/resources/application.properties
#100 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/104)
=> Disable the multipart resolver. (#101) 

src/main/java/com/vaadin/starter/skeleton/spring/Application.java
Fixes #116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/119)
=> Make application extend SpringBootServletInitializer

src/main/java/com/vaadin/starter/skeleton/spring/Application.java
Fixes #116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/120)
=> Make application extend SpringBootServletInitializer (#119)

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/122)
=> Update vaadin version to 13

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/123)
=> Fix branches names in readme

.travis.yml, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/124)
=> Pin Vaadin Platform + remove snapshort repos

.gitignore, pom.xml
Related to https://github.com/vaadin/beverage-starter-flow/issues/332
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/142)
=> Update the starter for a newer version of the plugin

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/141)
=> Use only one npm goal

.gitignore, pom.xml
Needs https://github.com/vaadin/spring/pull/429 to be merged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/143)
=> Use fixed dependency to avoid Spring Gson issues

pom.xml
Needed for Java 11 support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/151)
=> Update to Spring Boot 2.1

pom.xml
Needed for Java 11 support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/154)
=> CHERRY-PICK: spring 2.1 version bump

package-lock.json, package.json, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/157)
=> Update goal to prepare-frontend and generated files

src/main/resources/application.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/162)
=> Do not show Atmosphere debug (info) output by default

drivers.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/165)
=> Update to Chromedriver 75.0.3770.8 (#164)

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/178)
=> Fix bad link in readme

frontend/styles/README
Fixes #170 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/179)
=> Fix theming readme

src/main/resources/application.properties
Addresses vaadin/flow#5947
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/180)
=> Prevent server restarts after frontend changes

package-lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/193)
=> Update package-lock.json for 14.0.0.rc4

README.md, pom.xml
Fix #184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/190)
=> Fix run instructions in readme

pom.xml
In response to vaadin/flow#5973
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/198)
=> Update spring boot version

drivers.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/213)
=> Update chromedriver version

package-lock.json, package.json, pom.xml
Vaadin: 14.0.4
Flow: 3.0.0.alpha2
Router: 1.4.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/224)
=> chore: update dependencies

frontend/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/225)
=> fix: use flow.route API

package-lock.json, package.json, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/228)
=> chore: merge master into ccdm

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/229)
=> chore: update to flow-3.0.0.alpha3

.travis.yml, frontend/index.ts, package-lock.json, package.json, pom.xml
- Use vaadin 15.0-SNAPSHOT => this will be replaced with 15.0.0.alpha2 when it's out
Connected to https://github.com/vaadin/flow/issues/6367
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/234)
=> CCDM: use v15 snapshot

README.md
+ guilde readers to start.vaadin.com instead of vaadin.com/start
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/237)
=> fix: README typos

src/main/java/com/vaadin/starter/skeleton/spring/MessageBean.java
Fixes #241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/242)
=> Make MessageBean serializable

src/main/resources/application.properties
The issue in Flow has been fixed already a while ago.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/253)
=> chore: remove the workaround for flow/#5947

frontend/index.html
Connected to #258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/260)
=> fix: add default 100% height for body and router outlet

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/268)
=> Removed mentions to Flow and starter

src/main/java/com/vaadin/starter/skeleton/spring/AppShell.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/276)
=> Update to use AppShellConfigurator

.gitpod.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/283)
=> Run webpack dev server during GitPod prebuild

README.md, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/285)
=> Align as much as possible with ccdm branch

.gitpod.yml, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/286)
=> merge master

package.json, pnpm-lock.yaml, pom.xml, src/main/java/com/vaadin/starter/skeleton/spring/AppShell.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/289)
=> Upgrade to 15.0.0.alpha12

src/main/java/org/vaadin/example/Application.java, src/main/java/org/vaadin/example/GreetService.java, src/main/java/org/vaadin/example/MainView.java, src/test/java/org/vaadin/example/AbstractViewTest.java, src/test/java/org/vaadin/example/MainViewIT.java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/298)
=> Picks from master to V14

src/main/java/org/vaadin/example/AppShell.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/299)
=> Move AppShell to same package as everything else

tsconfig.json, types.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/312)
=> fix: add TypeScript declarations for .css module imports

src/test/java/org/vaadin/example/MainViewIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/313)
=> Create new tests for skeleton starter flow spring

src/test/java/org/vaadin/example/MainViewIT.java
(cherry picked from commit 86b7364b14ff7baa1de029f9f7980f650ccd583a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/314)
=> Create new tests for skeleton starter flow spring (#313)

README.md
Fix https://github.com/vaadin/flow/issues/7742
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/318)
=> Add live reload instructions to the Readme

src/main/java/org/vaadin/example/AppShell.java, src/main/java/org/vaadin/example/MainView.java
Fix https://github.com/vaadin/90min-dx-tasks/issues/132
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/323)
=> Remove PWA comment from the MainView and add it to the AppShell.java

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/333)
=> Remove random comment with no info

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/332)
=> The Vaadin pre-releases repo can contain snapshots

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/337)
=> Version 1 is where you typically start a project

src/main/java/org/vaadin/example/MainView.java
See https://github.com/vaadin/flow/issues/8038
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/336)
=> Do not show install prompt

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/338)
=> removes mention of flow from readme

src/main/resources/application.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/339)
=> Remove V14 Bower compatibility mode conf from V15

README.md
Fixes https://github.com/vaadin/90min-dx-tasks/issues/164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/350)
=> Fix profile name of integration test

README.md, pom.xml
Fixes: https://github.com/vaadin/90min-dx-tasks/issues/174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/355)
=> Fix profile name of integration test and ReadMe file

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/361)
=> Enhance `Running the Application` section

frontend/styles/vaadin-text-field-styles.css, src/main/java/org/vaadin/example/MainView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/363)
=> Master : Scope custom text field styling to a single instance

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/386)
=> Make the link a link

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/389)
=> Use latest Spring Boot (2.3.2)

.vscode/extensions.json
Same as #405 but for v17 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/416)
=> Recommended extensions for vscode

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-spring/431)
=> Use latest Spring Boot (2.4.0)

pom.xml
* Removed obsolete properties (already defined in parent pom)
* Updated to latest spring-boot version
=> pom.xml cleanup
